# Generated by Django 5.2.12 on 2026-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_proof_user_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
