# Generated by Django 5.2.12 on 2026-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_created_by_notice_document_notice_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('all', 'All'), ('staff', 'Staff'), ('security', 'Security')], default='all', max_length=20),
        ),
    ]
