# Generated by Django 5.2.12 on 2026-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
